Repository TreinaDev/esperto-fit-clientes, pull requests merged in 2020-10, with the labels that each got.

#46 Clean cpf register
  app/models/client.rb
  app/models/personal.rb
  config/locales/pt-BR.yml
  spec/features/client/client_register_spec.rb
  spec/features/personal/personal_trainer_register_spec.rb
  spec/models/client_spec.rb
  spec/models/personal_spec.rb
Labels: bug, help wanted

#52 Add alguns breadcrumbs
  app/controllers/application_controller.rb
  app/controllers/enrolls_controller.rb
  app/controllers/subsidiaries_controller.rb
  app/views/layouts/application.html.erb
  app/views/shared/_breadcrumbs.html.erb
  spec/features/breadcrumbs_spec.rb
  spec/requests/enroll_subsidiary_authorization_spec.rb
Labels: enhancement

#55 Correcao de mocks nos testes que envolvem filial/criacao de usuario
  spec/features/breadcrumbs_spec.rb
  spec/features/client_create_profile_spec.rb
  spec/features/client_edit_profile_spec.rb
Labels: bug

#63 Consumo da API de CPF banidos
  app/models/client.rb
  app/models/personal.rb
  app/models/subsidiary.rb
  app/views/enrolls/new.html.erb
  spec/models/client_spec.rb
  spec/models/personal_spec.rb
  spec/services/verify_partnership_service_spec.rb
Labels: bug
